################################################################################
# IMPORTANT: ORDER MATTERS!                                                    #
################################################################################

shell = "zsh"

# Templates: https://sheldon.cli.rs/Configuration.html#templates
[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}" # https://sheldon.cli.rs/Examples.html#deferred-loading-of-plugins-in-zsh
defer-more = "{% for file in files %}zsh-defer -t 0.5 source \"{{ file }}\"\n{% endfor %}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
proto = "ssh"
apply = ["source"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
proto = "ssh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
proto = "ssh"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
proto = "ssh"

[plugins.zsh-vim-mode]
github = "softmoth/zsh-vim-mode"
proto = "ssh"

# [plugins.git-open]
# github = "paulirish/git-open"
# proto = "ssh"

# [plugins.zsh-prompt-benchmark]
# github = "romkatv/zsh-prompt-benchmark" # Check ZSH prompt latency. To use, run `zsh-prompt-benchmark` and follow the instructions.
# proto = "ssh"

[plugins.git-fuzzy]
github = "bigH/git-fuzzy"
proto = "ssh"
apply = ["PATH"]

[plugins.you-should-use]
github = "MichaelAquilina/zsh-you-should-use"
proto = "ssh"

# Oh My Zsh plugins
[plugins.ohmyzsh]
github = "ohmyzsh/ohmyzsh"
proto = "ssh"
dir = "lib"
use = ["{command-not-found,completion,thefuck,compleat}.zsh"]
apply = ["defer"]

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
proto = "ssh"
